config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler404, handler500, handler400
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView


urlpatterns = [
    path('', include('accounts.urls')),
    path('groups/', include('course.urls')),
    path('search/', include('search.urls')),
    path('admin/', admin.site.urls),   
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# handler404 = 'app.views.handler404'
# handler500 = 'app.views.handler500'
# handler400 = 'app.views.handler400'

course/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
from django.core.validators import FileExtensionValidator
from django.db.models.signals import pre_save
from django.db.models import Q

# project import
from .utils import *




class GroupManager(models.Manager):
    def search(self, query=None):
        qs = self.get_queryset()
        if query is not None:
            or_lookup = (Q(title__icontains=query) | 
                         Q(summary__icontains=query)
                        )
            qs = qs.filter(or_lookup).distinct() # distinct() is often necessary with Q lookups
        return qs


class Group(models.Model):
    title = models.CharField(max_length=150, unique=True, verbose_name='Название')
    summary = models.TextField(null=True, blank=True, verbose_name='Описание')

    objects = GroupManager()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('group_detail', kwargs={'pk': self.pk})





class CourseAllocation(models.Model):
    lecturer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='allocated_lecturer')
    courses = models.ManyToManyField(Group, related_name='allocated_course')

    def __str__(self):
        return self.lecturer.get_full_name

    def get_absolute_url(self):
        return reverse('edit_allocated_course', kwargs={'pk': self.pk})


class Upload(models.Model):
    title = models.CharField(max_length=100)
    course = models.ForeignKey(Group, on_delete=models.CASCADE)
    file = models.FileField(upload_to='course_files/', validators=[FileExtensionValidator(['pdf', 'docx', 'doc', 'xls', 'xlsx', 'ppt', 'pptx', 'zip', 'rar', '7zip'])])
    updated_date = models.DateTimeField(auto_now=True, auto_now_add=False, null=True)
    upload_time = models.DateTimeField(auto_now=False, auto_now_add=True, null=True)
    last_date = models.DateTimeField(blank=True, null=False, verbose_name="Сдать до ")

    def __str__(self):
        return str(self.file)[6:]

    def get_extension_short(self):
        ext = str(self.file).split(".")
        ext = ext[len(ext)-1]

        if ext == 'doc' or ext == 'docx':
            return 'word'
        elif ext == 'pdf':
            return 'pdf'
        elif ext == 'xls' or ext == 'xlsx':
            return 'excel'
        elif ext == 'ppt' or ext == 'pptx':
            return 'powerpoint'
        elif ext == 'zip' or ext == 'rar' or ext == '7zip':
            return 'archive'

    def delete(self, *args, **kwargs):
        self.file.delete()
        super().delete(*args, **kwargs)


class CourseOffer(models.Model):
	"""NOTE: Only department head can offer semester courses"""
	dep_head = models.ForeignKey("accounts.DepartmentHead", on_delete=models.CASCADE)

	def __str__(self):
		return "{}".format(self.dep_head)

class AddStudTask(models.Model):
    student = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='addstudent_list')
    exercise = models.ForeignKey(Upload, on_delete=models.CASCADE)
    lecturer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='aadstudent_lecturer')
    updated_date = models.DateTimeField(auto_now=True, auto_now_add=False, null=True)
    upload_time = models.DateTimeField(auto_now=False, auto_now_add=True, null=True)
    answer = models.FileField(upload_to='student_files/', validators=[FileExtensionValidator(['pdf', 'docx', 'doc', 'xls', 'xlsx', 'ppt', 'pptx', 'zip', 'rar', '7zip'])])
    mark = models.IntegerField(default=0)

    @property
    def answer_filename(self):
        return os.path.basename(self.answer.name)

class Notification(models.Model):
    notif_user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='notification_user')
    for_user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='for_user')
    exercise_notif = models.ForeignKey(AddStudTask, on_delete=models.CASCADE)
    messages = models.TextField(null=True, blank=True, verbose_name='Сообщение')
    is_viewed = models.BooleanField(default=False, verbose_name='Просмотренно')
    time_create = models.DateTimeField(auto_now_add=True, verbose_name="Время создания")
    last_date = models.ForeignKey(Upload, on_delete=models.CASCADE, null=False, blank=True, related_name='notifications_date')


class Comments(models.Model):
    from_user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    task = models.ForeignKey(AddStudTask, on_delete=models.CASCADE)
    time_create = models.DateTimeField(auto_now_add=True, verbose_name="Время создания")
    messages = models.TextField(null=True, blank=True, verbose_name='Сообщение')
    

templates/upload/upload_file_form.html
{% extends 'base.html' %}
{% block title %}{{ title }}{% endblock title %}
{% load crispy_forms_tags %}

{% block content %}

<div id="input-nav"><a href="{% url 'home' %}" class="primary1">Главная</a>
     <i>&rsaquo;</i> <a href="{% url 'groups' %}" class="primary1">Группы</a> 
     <a href="{% url 'group_detail' course.pk %}" class="primary1"> {{ course.group }}</a>  
       Загрузка файлов</div>

<p class="title-1">Загрузка файлов для <span style="text-transform: lowercase;">{{ course }}</span></p>
<div class="title-line"></div><br>

{% if messages %}
    {% for message in messages %}
        {% if message.tags == 'error' %}
            <div class="alert alert-danger">
                <i class="fas fa-exclamation-circle"></i>{{ message }}
            </div>
        {% else %}
            <div class="alert alert-success">
                <i class="fas fa-check-circle"></i>{{ message }}
            </div>
        {% endif %}
    {% endfor %}
{% endif %}

<div class="row">
<div class="col-md-8 p-0 mx-auto">
    <div class="card">
    <p class="form-title">Загрузка файлов</p><br>
    <form action="" method="POST" enctype="multipart/form-data">{% csrf_token %}
        <div class="container">
            
            <div class="form-group">
                <b>Тема</b>{{ form.title }}
                <span class="danger">{{ form.title.errors }}</span>
            </div>
            <div class="form-group">
                <b>Файл</b><br>{{ form.file }}
                <span class="danger">{{ form.file.errors }}</span>
            </div>
            <p class="text-orange"><b>Допустимые расширения: </b>pdf, docx, doc, xls, xlsx, ppt, pptx, zip, rar, 7zip</p>
            <div class="form-group">
                <select hidden name="course" required="" id="id_course">
                    <option value="{{ course.pk }}" selected>{{ course }}</option>
                </select>
            </div>

            <div class="form-group">
                <b>{{ form.last_date.label }}</b>{{ form.last_date }}
                <span class="danger">{{ form.last_date.errors }}</span>
            </div>

            <div class="form-group">
                <button class="btn btn-primary" type="submit">Загрузить</button>
                <a class="btn btn-danger" href="{% url 'group_detail' course.pk %}" style="float: right;">Отмена</a>
            </div>

        </div>
        <br>
        <div class="card">
    </form>
</div>
</div>

{% endblock content %}